// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var NextSeo = require("next-seo");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(config, children) {
  return ReasonReact.wrapJsForReason(NextSeo.default, {
              config: Js_undefined.fromOption(config)
            }, children);
}

exports.make = make;
/* next-seo Not a pure module */
